---
title: FIXEE
baseurl: "/"
permalink: "/:title/"
layout_style: overflow
palette: orange
header:
  title: FIXEE
  tagline: Sarpeet Kaur (19051837)
  profile_img: "/images/Untitled-1.png"
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: "&copy; All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
